name: cep_app
description: "Proyecto para el Centro de Estudiantes de  la Politecnica"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  qr_flutter: ^4.1.0
  go_router: ^14.7.1
  qr_code_scanner_plus: ^2.0.9+1
  camera: ^0.11.0+2
  firebase_storage: ^12.4.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  shared_preferences: ^2.5.2
  freezed: ^2.5.8
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  either_dart: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
