name: cep_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  qr_flutter: ^4.1.0
  go_router: ^14.7.1
  qr_code_scanner_plus: ^2.0.9+1
  camera: ^0.11.0+2
  firebase_storage: ^12.4.1
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
